info:
  name: 113. GetConfigEventGrouping
  type: http
  seq: 92

http:
  method: GET
  url: "{{url}}/general/GetConfigEventGrouping"
  auth:
    type: bearer
    token: "{{Token_productor}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
